version: "3.9"
services:
  db:
    image: "postgres:13.7-alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vwire_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]  # -h localhost -p 5432
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/vwire_db
      - SIGN_SECRET_KEY=e025ce978c17a012241a16ca1457e2d4c4f9d7e8f47c2cd2b5ac629c43c64db4  # openssl rand -hex 32
      - SIGN_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
volumes:
  db_data:
    driver: local
