version: "3.9"
services:
  db:
    image: "postgres:13.7-alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vwire_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]  # -h localhost -p 5432
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
volumes:
  db_data:
    driver: local
