"""scooters table

Revision ID: 68f69d7efcf8
Revises: 13626c84e07a
Create Date: 2022-11-26 00:58:01.774842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68f69d7efcf8'
down_revision = '13626c84e07a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scooters',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scooters_code'), 'scooters', ['code'], unique=True)
    op.create_index(op.f('ix_scooters_id'), 'scooters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scooters_id'), table_name='scooters')
    op.drop_index(op.f('ix_scooters_code'), table_name='scooters')
    op.drop_table('scooters')
    # ### end Alembic commands ###
